### PR TITLE
Use Syntax Theme Colors

### PR DESCRIPTION
**Pull request by chrisblatchley**
I think it would be cool to use the syntax theme colors for highlighting words. I've tried it with a few themes and I think it looks a lot better when it matches the cursor color.

I don't have an opinion on what colors the background colors should be, as I never use them. However, this PR might be a good place to decide.

### CODE REVIEW

**Comment by richrace** [comment]
I like this. But I think it should be an option to use the theme colour. 

What do you think?

**Comment by chrisblatchley** [comment]
Yeah, that sounds great to me. If you have an opinion on themed colors for background highlighting as well that would be cool to add in. I'm not sure how to add options, i've only trivially added this feature for myself. Maybe when you get a free moment, you can add that option?

**Comment by hgoodman** [comment]
+1 for using theme colors. Modifying luminance of the border theme color for text that is actually selected (or not selected) would also be a great improvement. FWIW, I think that non-rounded corners look better too.

**Comment by TheFinalDawn** [comment]
Great Idea!

**Pull request closed without merging**
